spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 本地
#    url: ENC(YtM8eOUx/ZstPau/Ovsrvp0yTWwNG5Q2IeZd3ha6hO6SnVWLwec97OcmTYdwrU4K70bxxRnc2iB9ixnxyoCINPRG6p2zEoEAdTWreCbJaLH+x5RNTrppwcZ434YyB8UGMPK9ub5hlZo=)
#    username: ENC(6zCJB5ojsIhi552jSTHdwA==)
#    password: ENC(PX31Oz6CWL9//cY1YFnV2STMJyS73TvT)
  # 远程
    url: ENC(7Wvqc1NRK9VJZvArxt/X+Y3xyuB3Do4vfq0TltaxN7zPjy1PzPAZ2I2+YoZIMcS+YjLTKK+2udeSZ/1BTxGDgpT9zUXkXWvl6SBkUFOtFjDvo8fdtqOx3gX+ZOIT/enC2b+8d/3/9/1TXeOtnuxQdA==)
    username: ENC(W2W7MkYuuCa1/qhR4Gvzaw==)
    password: ENC(NOZbMSQVBbXBFULwvXGRoST+hU+RJV4M)
  redis:
    database: 4
    host: ENC(ZcXx0LXB7u1YaCEwiGLJa2Nkr3ARs6Xl)
    password: ENC(YpdLqa+kzbGC7I3gemW0CDaifGforTz5)
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    打印 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
